[package]
name = "ordermap"
version = "0.1.2"
authors = ["bluss"]
documentation = "https://docs.rs/ordermap/0.1/"
repository = "https://github.com/bluss/ordermap"
license = "Apache-2.0/MIT"
description = "A hash table with consistent order and fast iteration."

[lib]
bench = false

[dependencies]

[dev-dependencies]
itertools = "0.5.1"
rand = "0.3"
quickcheck = "0.3.1"
fnv = "1.0"
lazy_static = "0.2"

[features]
# for testing only, of course
test_low_transition_point = []

[profile.bench]
debug = true
