on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Continuous integration

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rust: 1.36.0 # MSRV
            features:
          - rust: stable
            features: serde
          - rust: stable
            features: rayon
          - rust: stable
            features: std
          - rust: beta
            features:
          - rust: nightly
            bench: 1
          - rust: nightly
            features: test_low_transition_point
          - rust: 1.36.0
            target: thumbv6m-none-eabi
            features:
          - rust: stable
            target: thumbv6m-none-eabi
            features:

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Add target
        run: rustup target add ${{ matrix.target }}
        if: matrix.target != ''
      - name: Tests (custom target)
        if: matrix.target != ''
        run: |
          cargo build -vv --target=${{ matrix.target }}
          cargo build -v -p test-nostd --target=${{ matrix.target }}
      - name: Tests
        if: matrix.target == ''
        run: |
          cargo build --verbose --features "${{ matrix.features }}"
          cargo doc --verbose --features "${{ matrix.features }}"
          cargo test --verbose --features "${{ matrix.features }}"
          cargo test --release --verbose --features "${{ matrix.features }}"
      - name: Tests (serde)
        if: matrix.features == 'serde'
        run: |
          cargo test --verbose -p test-serde
      - name: Test run benchmarks
        if: matrix.bench != ''
        run: cargo test -v --benches

  clippy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - beta
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: clippy
      - run: cargo clippy

